document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.avatar-side-card,.signal').forEach(el=>el.remove()));
const projectData={
 satylens:{type:'PRODUCT',title:'SatyLens',body:'Manifest V3 Chrome extension for full-page and area screenshots and screen recording with annotation tools, offline IndexedDB gallery, sharing workflows, FastAPI/Supabase integration, Google Drive OAuth, Cloudflare R2, analytics/admin views and automated headless Chrome + Pytest/backend tests.',tags:['Chrome MV3','FastAPI','Supabase','Pytest'],url:'https://github.com/SanFlash/SatyLens'},
 satyon:{type:'AI RESEARCH',title:'SATYON-AI',body:'Multi-source AI search and research aggregator integrating Google, ChatGPT, DeepSeek, Wikipedia, GitHub, Kaggle, arXiv and YouTube, with query classification, AI summarization, developer/research modes and caching.',tags:['AI','Search','Summarization','Caching'],url:'https://github.com/SanFlash/SATYON-AI'},
 cricapp:{type:'REAL-TIME APP',title:'Cric-App',body:'Full-stack corporate cricket management and analytics platform with FastAPI, SQLAlchemy and WebSockets. Covers player/squad management, live scoring, performance/form/rating engines, win prediction, XI recommendations, tournaments, standings, achievements, notifications and AI insights.',tags:['FastAPI','SQLAlchemy','WebSockets'],url:'https://github.com/SanFlash/cric-app'},
 satynqa:{type:'QA PLATFORM',title:'SatynQA',body:'QA-focused web testing and automation project for exploring structured test workflows, testing utilities and quality-engineering practices.',tags:['QA','Automation','Testing'],url:'https://github.com/SanFlash/SatynQA'},
 skbh:{type:'SPORTS APP',title:'SKBH Table Tennis',body:'Table tennis tournament and match-management application for organizing players, matches and competition workflows.',tags:['Python','Web','Sports'],url:'https://github.com/SanFlash/SKBH_TT'},
 droidtestx:{type:'MOBILE QA',title:'DroidTestX',body:'Mobile E2E automation framework using Python, Appium, Pytest, UiAutomator2 and Page Object Model, covering login, product browsing, cart, checkout, shipping, payment and order-review workflows.',tags:['Python','Appium','Pytest','UiAutomator2','POM'],url:'https://github.com/SanFlash/DroidTestX-Appium-Automation'},
 darshanqa:{type:'WEB QA',title:'Darshan Hotel Automation',body:'Python Playwright + Pytest + Allure framework with POM, layered fixtures, utilities, data-driven tests, multi-environment configuration, failure screenshots/logging, GitHub Actions and automated reporting dashboards.',tags:['Playwright','Pytest','Allure','GitHub Actions'],url:'https://github.com/SanFlash/DarshanHotel-AutomationTesting'},
 codesight:{type:'DEV TOOL',title:'AI Code Analyzer',body:'Flask developer utility for Python syntax/lint diagnostics, complexity and maintainability metrics, optional AI suggestions and proposed corrections, plus analysis, execution and health APIs.',tags:['Flask','Python','AI','Code Analysis'],url:'https://github.com/SanFlash/AI_Code_Analyser-Teacher'},
 super15:{type:'ML × CRICKET',title:'Super15',body:'IPL player prediction application using player statistics, recent form and venue history. Demonstrates Python, Flask, data processing and ML-backed application development.',tags:['Python','Flask','ML','Analytics'],url:'https://github.com/SanFlash/IPL_Predictor'},
 sum:{type:'FULL STACK',title:'Scholar Ultimate Matrix',body:'Educational portal for student tracking and content sharing, demonstrating ASP.NET development, SQL Server integration, database workflows and application-testing exposure.',tags:['ASP.NET','C#','SQL Server','HTML/CSS'],url:'https://github.com/SanFlash/Scholar_Ultimate_Matrix'},
 dashboards:{type:'DATA',title:'Power BI & Python Dashboards',body:'Interactive analysis projects covering IPL trends, anime analytics and EV population data using Python, Pandas, Matplotlib, exploratory data analysis, statistical analysis and dashboard development.',tags:['Power BI','Python','Pandas','Matplotlib'],url:'https://github.com/SanFlash/IPL_08-24_Data_Analysis.com'},
 satyenai:{type:'AI × EDUCATION',title:'Satyen78AI',body:'AI-powered study assistant for conceptual revision and smart note generation with a responsive web interface and optimized backend workflows.',tags:['AI','Flask','Web','Education'],url:'https://github.com/SanFlash/Satyen78beruAI'}
};
const projectLinks={
 cricapp:{github:'https://github.com/SanFlash/cric-app',live:'https://cric-app-gilt.vercel.app/',download:'https://median.co/share/xlzbxkr#apk'},
 satyon:{github:'https://github.com/SanFlash/SATYON-AI',live:'https://satyon-ai.vercel.app/',download:'https://median.co/share/dyemzre#apk'},
 satynqa:{github:'https://github.com/SanFlash/SatynQA',live:'https://satyn-qa.vercel.app/',download:'https://median.co/share/rdzkyew#apk'},
 skbh:{github:'https://github.com/SanFlash/SKBH_TT',live:'https://tt-clash78.vercel.app/',download:'https://median.co/share/bnlwlok#apk'},
 codesight:{github:'https://github.com/SanFlash/AI_Code_Analyser-Teacher',live:'https://ai-code-analyser-teacher.onrender.com/'},
 satyenai:{github:'https://github.com/SanFlash/Satyen78beruAI',live:'https://satyen78beruai.onrender.com/'}
};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const loadMotionCSS=()=>{if(document.querySelector('link[data-motion-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='responsive-motion.css';l.dataset.motionCss='true';document.head.appendChild(l)};loadMotionCSS();
const nav=$('#topNav'),toggle=$('#navToggle');toggle?.addEventListener('click',()=>nav.classList.toggle('menu-open'));$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('menu-open')));
const glow=$('#cursorGlow');window.addEventListener('pointermove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
const avatar=$('#heroAvatar');if(avatar){avatar.src='image/avatar.png';avatar.loading='eager';avatar.decoding='async';avatar.onerror=()=>{avatar.src='https://raw.githubusercontent.com/SanFlash/SanFlash-SatyendraNamdeoPortfolio/main/image/avatar.png'}}
const orb=$('#orb'),scene=$('#orbScene'),caption=$('#orbCaption');scene?.addEventListener('pointermove',e=>{const r=scene.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;if(orb)orb.style.transform=`rotateX(${y*-22}deg) rotateY(${x*30}deg) translateZ(24px)`;if(caption)caption.textContent='Interactive QA core · '+Math.round((x+.5)*100)+'% signal'});scene?.addEventListener('pointerleave',()=>{if(orb)orb.style.transform='';if(caption)caption.textContent='Move your cursor around'});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(el=>observer.observe(el));
$$('.magnetic').forEach(btn=>{btn.addEventListener('pointermove',e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});btn.addEventListener('pointerleave',()=>btn.style.transform='')});
$$('.project-card,.capability-grid>div,.mini-metrics>div').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--px',((x+.5)*100)+'%');card.style.setProperty('--py',((y+.5)*100)+'%');card.style.transform=`perspective(900px) rotateX(${y*-5}deg) rotateY(${x*7}deg) translateY(-7px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
function openProject(key){const p=projectData[key];if(!p)return;$('#modalType').textContent=p.type;$('#modalTitle').textContent=p.title;$('#modalBody').textContent=p.body;$('#modalTags').innerHTML=p.tags.map(t=>`<span>${t}</span>`).join('');const links=projectLinks[key];$('#modalLink').href=links?.github||p.url;$('#projectModal').classList.add('open');$('#projectModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeProject(){$('#projectModal').classList.remove('open');$('#projectModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function bindProjectCard(card){card.addEventListener('click',e=>{if(e.target.closest('a'))return;openProject(card.dataset.project)})}
$$('.project-card').forEach(bindProjectCard);$('#modalClose')?.addEventListener('click',closeProject);$('.modal-backdrop')?.addEventListener('click',closeProject);document.addEventListener('keydown',e=>e.key==='Escape'&&closeProject());
const filterMap={Playwright:['Playwright'],Pytest:['Pytest'],Appium:['Appium'],Python:['Python'],JavaScript:['JavaScript'],API:['API'],SQL:['SQL'],AI:['AI'],FastAPI:['FastAPI']};$$('#skillCloud .skill').forEach(btn=>btn.addEventListener('click',()=>{const f=btn.dataset.filter;$$('#skillCloud .skill').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.project-card').forEach(card=>{if(f==='all'){card.classList.remove('hidden-card');return}const tags=[...card.querySelectorAll('.tags span')].map(x=>x.textContent.toLowerCase()),wanted=(filterMap[f]||[f]).map(x=>x.toLowerCase());card.classList.toggle('hidden-card',!wanted.some(w=>tags.some(t=>t.includes(w))))})}));
const grid=$('.project-grid');const archive=[['satyon','07','SATYON-AI','AI RESEARCH'],['darshanqa','08','Darshan Hotel Automation','WEB QA'],['super15','10','Super15','ML × CRICKET'],['sum','11','Scholar Ultimate Matrix','FULL STACK'],['dashboards','12','Power BI & Python Dashboards','DATA'],['satyenai','13','Satyen78AI','AI × EDUCATION'],['satynqa','14','SatynQA','QA PLATFORM'],['skbh','15','SKBH Table Tennis','SPORTS APP']];archive.forEach(([key,index,title,type])=>{if(!grid||grid.querySelector(`[data-project="${key}"]`))return;const p=projectData[key],card=document.createElement('article');card.className='project-card reveal archive-card';card.dataset.project=key;card.innerHTML=`<div class="project-top"><span class="project-index">${index}</span><span class="project-type">${type}</span></div><h3>${title}</h3><p>${p.body}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="project-more" type="button">Inspect project <i class="bi bi-arrow-right"></i></button>`;grid.appendChild(card);observer.observe(card);bindProjectCard(card)});
['intellitest','testerwish','recruitsync'].forEach(key=>document.querySelector(`.project-card[data-project="${key}"]`)?.remove());
const projectLinkStyle=document.createElement('style');projectLinkStyle.textContent='.project-links{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.project-links a{display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border:1px solid rgba(255,255,255,.12);border-radius:10px;text-decoration:none;font-size:.82rem;font-weight:700;color:inherit;background:rgba(255,255,255,.035);transition:transform .2s ease,border-color .2s ease,background .2s ease}.project-links a:hover{transform:translateY(-2px);border-color:rgba(98,232,255,.55);background:rgba(98,232,255,.08)}.project-links .live-link{border-color:rgba(98,232,255,.3)}.project-links .download-link{border-color:rgba(120,255,180,.3)}';document.head.appendChild(projectLinkStyle);
function addProjectLinks(){Object.entries(projectLinks).forEach(([key,links])=>{document.querySelectorAll(`.project-card[data-project="${key}"]`).forEach(card=>{if(card.querySelector('.project-links'))return;const wrap=document.createElement('div');wrap.className='project-links';wrap.innerHTML=`<a class="github-link" href="${links.github}" target="_blank" rel="noopener noreferrer"><i class="bi bi-github"></i> GitHub</a>${links.live?`<a class="live-link" href="${links.live}" target="_blank" rel="noopener noreferrer"><i class="bi bi-box-arrow-up-right"></i> Live Demo</a>`:''}${links.download?`<a class="download-link" href="${links.download}" target="_blank" rel="noopener noreferrer" download><i class="bi bi-download"></i> Download App</a>`:''}`;card.appendChild(wrap)})})}addProjectLinks();
const hero=$('.hero');if(hero){const canvas=document.createElement('canvas');canvas.className='hero-particles';canvas.setAttribute('aria-hidden','true');hero.prepend(canvas);const ctx=canvas.getContext('2d');let w=0,h=0,particles=[];const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;function resize(){const d=Math.min(devicePixelRatio||1,2);w=hero.clientWidth;h=hero.clientHeight;canvas.width=w*d;canvas.height=h*d;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);const count=Math.min(90,Math.max(38,Math.floor(w*h/17000)));particles=Array.from({length:count},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3,r:Math.random()*1.5+.4}))}function draw(){ctx.clearRect(0,0,w,h);for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='rgba(98,232,255,.48)';ctx.fill()}for(let i=0;i<particles.length;i++)for(let j=i+1;j<particles.length;j++){const a=particles[i],b=particles[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<120){ctx.strokeStyle=`rgba(98,232,255,${(1-d/120)*.14})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}if(!reduce)requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw()}
const progress=document.createElement('div');progress.className='scroll-progress';document.body.appendChild(progress);addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?(scrollY/max)*100:0)+'%'},{passive:true});
const avatarStage=$('#avatarStage');if(avatarStage&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let tx=0,ty=0,rx=0,ry=0,raf=0;const move=e=>{const r=avatarStage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tx=x*16;ty=y*12;rx=y*-4;ry=x*6;avatarStage.style.setProperty('--mx',((x+.5)*100)+'%');avatarStage.style.setProperty('--my',((y+.5)*100)+'%');if(!raf)raf=requestAnimationFrame(()=>{avatarStage.style.transform=`translate3d(${tx}px,${ty}px,0) rotateX(${rx}deg) rotateY(${ry}deg)`;raf=0})};avatarStage.addEventListener('pointermove',move);avatarStage.addEventListener('pointerleave',()=>{avatarStage.style.transform='';avatarStage.style.setProperty('--mx','50%');avatarStage.style.setProperty('--my','45%')})}
$$('.project-card,.capability-card,.domain-card,.metric-card,.motion-node,.explore-card').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--px',`${((e.clientX-r.left)/r.width)*100}%`);card.style.setProperty('--py',`${((e.clientY-r.top)/r.height)*100}%`)}));
const sections=$$('main section[id]'),navLinks=$$('.nav-links a');if('IntersectionObserver' in window&&sections.length&&navLinks.length){const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}),{rootMargin:'-30% 0px -60% 0px',threshold:0});sections.forEach(s=>navObserver.observe(s))}
if('ontouchstart' in window)document.documentElement.classList.add('touch-device');const titleParts=['Satyendra Kumar Namdeo','QA Automation Engineer','Playwright · Appium · AI'];let titleIndex=0;setInterval(()=>{if(!document.hidden){titleIndex=(titleIndex+1)%titleParts.length;document.title=titleParts[titleIndex]+' — Portfolio'}},3600);document.title='Satyendra Kumar Namdeo — QA Automation × AI';